# Generated by Django 4.0.4 on 2022-06-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_number', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('interest', models.DecimalField(decimal_places=3, max_digits=6)),
                ('account_opened', models.DateTimeField(verbose_name='Inception date')),
                ('transit_number', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('running_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trans_timestamp', models.DateTimeField()),
                ('trans_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('access_card', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('PIN', models.IntegerField(max_length=5)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('client_since', models.DateTimeField(verbose_name='Client since')),
            ],
        ),
    ]
