# Generated by Django 4.0.4 on 2022-05-27 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telagents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='trans_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
