# Generated by Django 4.0.4 on 2022-06-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telagents', '0002_bankaccount_transaction_user_delete_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='referring_user',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='access_card',
            field=models.IntegerField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
