# Generated by Django 4.0.4 on 2022-06-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telagents', '0003_rename_user_transaction_referring_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='referring_user',
            new_name='user',
        ),
    ]
