# Generated by Django 4.0.4 on 2022-06-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telagents', '0004_rename_referring_user_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='id',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
