# Generated by Django 4.0.4 on 2022-06-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telagents', '0005_remove_bankaccount_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account',
            new_name='access_card',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='account_number',
        ),
    ]
